=== willy182/ticket-order-simulation/ticketing/api/jsonschema/transaction/save.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "JSON Schema for save",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"customer_name": {
			"type": "string",
			"minLength": 3,
			"maxLength": 255,
			"errorMessage": "panjang minimal 3 karakter dan maksimal 255 karakter"
		},
		"customer_email": {
			"type": "string",
			"format": "email",
			"errorMessage": "format email salah"
		},
		"customer_phone": {
			"type": "string",
			"minLength": 9,
			"maxLength": 15,
			"errorMessage": "panjang minimal 9 karakter dan maksimal 15 karakter"
		},
		"qty": {
			"type": "integer",
			"minimum": 1,
			"errorMessage": "minimal booking tiket adalah 1"
		},
		"ticket_id": {
			"type": "number",
			"minimum": 0,
			"errorMessage": "tiket ID tidak boleh negatif"
		},
		"status": {
			"type": "string",
			"enum": ["SUCCESS", "PENDING", "FAILED"],
			"errorMessage": "status tidak valid"
		}
	},
	"required": [ "customer_name", "customer_email", "customer_phone", "qty", "ticket_id", "status" ],
	"additionalProperties": false
}

=== willy182/ticket-order-simulation/script-war/war_ticket.json
[
    {
        "customer_name": "ulfa_fauziah_1",
        "customer_email": "ulfa.fauziah1@gmail.com",
        "customer_phone": "085959519085",
        "qty": 2,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "oki_kurniawan_2",
        "customer_email": "oki.kurniawan2@gmail.com",
        "customer_phone": "085134171696",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "lucky_anggraini_3",
        "customer_email": "lucky.anggraini3@gmail.com",
        "customer_phone": "086763606033",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "sinta_permatasari_4",
        "customer_email": "sinta.permatasari4@gmail.com",
        "customer_phone": "087011932216",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "oki_permatasari_5",
        "customer_email": "oki.permatasari5@gmail.com",
        "customer_phone": "086602426217",
        "qty": 1,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "tono_anggraini_6",
        "customer_email": "tono.anggraini6@gmail.com",
        "customer_phone": "088736279042",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "zaki_anggraini_7",
        "customer_email": "zaki.anggraini7@gmail.com",
        "customer_phone": "088567865548",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "heri_nugroho_8",
        "customer_email": "heri.nugroho8@gmail.com",
        "customer_phone": "081925221825",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "zaki_setiawan_9",
        "customer_email": "zaki.setiawan9@gmail.com",
        "customer_phone": "084737748637",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "indah_nugroho_10",
        "customer_email": "indah.nugroho10@gmail.com",
        "customer_phone": "085996897477",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "galih_maharani_11",
        "customer_email": "galih.maharani11@gmail.com",
        "customer_phone": "085306529701",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "budi_nugroho_12",
        "customer_email": "budi.nugroho12@gmail.com",
        "customer_phone": "085122937612",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "wahyu_setiawan_13",
        "customer_email": "wahyu.setiawan13@gmail.com",
        "customer_phone": "087067606439",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "amel_nugroho_14",
        "customer_email": "amel.nugroho14@gmail.com",
        "customer_phone": "088193326510",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "zaki_santoso_15",
        "customer_email": "zaki.santoso15@gmail.com",
        "customer_phone": "084022498297",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "putri_maharani_16",
        "customer_email": "putri.maharani16@gmail.com",
        "customer_phone": "086308683397",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "fajar_fauziah_17",
        "customer_email": "fajar.fauziah17@gmail.com",
        "customer_phone": "088614167254",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "budi_syahputra_18",
        "customer_email": "budi.syahputra18@gmail.com",
        "customer_phone": "085723979949",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "mega_setiawan_19",
        "customer_email": "mega.setiawan19@gmail.com",
        "customer_phone": "083474230521",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "andi_hakim_20",
        "customer_email": "andi.hakim20@gmail.com",
        "customer_phone": "084654996839",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "vina_ramadhan_21",
        "customer_email": "vina.ramadhan21@gmail.com",
        "customer_phone": "089790726118",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "eko_lestari_22",
        "customer_email": "eko.lestari22@gmail.com",
        "customer_phone": "085582871432",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "andi_anggraini_23",
        "customer_email": "andi.anggraini23@gmail.com",
        "customer_phone": "088900036157",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "sinta_susilo_24",
        "customer_email": "sinta.susilo24@gmail.com",
        "customer_phone": "081492807392",
        "qty": 1,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "vicky_lestari_25",
        "customer_email": "vicky.lestari25@gmail.com",
        "customer_phone": "089360156474",
        "qty": 1,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "joko_ramadhan_26",
        "customer_email": "joko.ramadhan26@gmail.com",
        "customer_phone": "087558139683",
        "qty": 2,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "reza_wijaya_27",
        "customer_email": "reza.wijaya27@gmail.com",
        "customer_phone": "088405682455",
        "qty": 1,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "zaki_handayani_28",
        "customer_email": "zaki.handayani28@gmail.com",
        "customer_phone": "087222963159",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "taufik_saputra_29",
        "customer_email": "taufik.saputra29@gmail.com",
        "customer_phone": "085434548985",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "mega_permatasari_30",
        "customer_email": "mega.permatasari30@gmail.com",
        "customer_phone": "087284224246",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "dian_lestari_31",
        "customer_email": "dian.lestari31@gmail.com",
        "customer_phone": "088742982852",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "joko_pratama_32",
        "customer_email": "joko.pratama32@gmail.com",
        "customer_phone": "085710725027",
        "qty": 2,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "maman_maharani_33",
        "customer_email": "maman.maharani33@gmail.com",
        "customer_phone": "085943054804",
        "qty": 2,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "dewi_hakim_34",
        "customer_email": "dewi.hakim34@gmail.com",
        "customer_phone": "084930241037",
        "qty": 1,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "rudi_hakim_35",
        "customer_email": "rudi.hakim35@gmail.com",
        "customer_phone": "081995180623",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "rudi_saputra_36",
        "customer_email": "rudi.saputra36@gmail.com",
        "customer_phone": "084774111530",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "nando_ramadhan_37",
        "customer_email": "nando.ramadhan37@gmail.com",
        "customer_phone": "087592131913",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "erwin_syahputra_38",
        "customer_email": "erwin.syahputra38@gmail.com",
        "customer_phone": "084495635466",
        "qty": 2,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "vicky_fauziah_39",
        "customer_email": "vicky.fauziah39@gmail.com",
        "customer_phone": "086942750163",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "qori_pratama_40",
        "customer_email": "qori.pratama40@gmail.com",
        "customer_phone": "087417436930",
        "qty": 2,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "andi_syahputra_41",
        "customer_email": "andi.syahputra41@gmail.com",
        "customer_phone": "086973653490",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "prima_saputra_42",
        "customer_email": "prima.saputra42@gmail.com",
        "customer_phone": "088499299943",
        "qty": 1,
        "ticket_id": 1,
        "status": "FAILED"
    },
    {
        "customer_name": "hana_wijaya_43",
        "customer_email": "hana.wijaya43@gmail.com",
        "customer_phone": "082201917827",
        "qty": 2,
        "ticket_id": 1,
        "status": "PENDING"
    },
    {
        "customer_name": "mega_nugroho_44",
        "customer_email": "mega.nugroho44@gmail.com",
        "customer_phone": "082418240014",
        "qty": 1,
        "ticket_id": 1,
        "status": "SUCCESS"
    },
    {
        "customer_name": "imam_ramadhan_45",
        "customer_email": "imam.ramadhan45@gmail.com",
